GEscola/GEscola/Models/Users.cs
using GEscola.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GEscola.Models
{
    public class Users
    {
        public Person person { get; set; }
        public string role { get; set; }

        
        [Required(ErrorMessage = "O campo \"{0}\" é obrigatório.")]
        [DataType(DataType.Text)]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Required(ErrorMessage = "O campo \"{0}\" é obrigatório.")]
        [DataType(DataType.Text)]
        [Display(Name = "Nome da Escola")]
        public string SchoolName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data")]
        public DateTime Birthdate { get; set; }

        [Required(ErrorMessage = "O campo \"{0}\" é obrigatório.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [EmailAddress]
        [Display(Name = "Email Secundário")]
        public string SecondaryEmail { get; set; }

        [Display(Name = "PIN Parental")]
        public int ParentalPIN { get; set; }

        [Required(ErrorMessage = "O campo \"{0}\" é obrigatório.")]
        [StringLength(100, ErrorMessage = "A nova password deve de conter pelo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required(ErrorMessage = "O campo \"{0}\" é obrigatório.")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar password")]
        [Compare("Password", ErrorMessage = "As passwords inseridas não coincidem.")]
        public string ConfirmPassword { get; set; }
    }
}

GEscola/GEscola/Controllers/UsersController.cs
using GEscola.Data;
using GEscola.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace GEscola.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Person> _userManager;
        private readonly SignInManager<Person> _signInManager;
        private readonly IEmailSender _emailSender;

        public UsersController(ApplicationDbContext context, UserManager<Person> userManager, SignInManager<Person> signInManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
        }

        // GET: Users
        /// <summary>
        /// This async method of UsersController returns the Index View
        /// that shows all the active users of the logged user school.
        /// </summary>
        /// <returns>View(List of Person usersToShow)</returns>
        public async Task<ActionResult> Index()
        {
            var users = await _context.Users.Where(u => u.isDeleted == false && u.SchoolName == Utils.getSchoolName(User, _context)).ToListAsync();
            users.Remove((Person)Utils.UsersOfRole("Admin", User, _context)[0]);
            return View(users);
        }

        // GET: Users/Students
        /// <summary>
        /// This method of UsersController returns the Students View that shows
        /// all the active users with the "Student" role of the logged user school.
        /// </summary>
        /// <returns>View(List of Person usersToShow)</returns>
        public ActionResult Students()
        {
            return View(Utils.UsersOfRole("Student", User, _context));
        }

        // GET: Users/Teachers
        /// <summary>
        /// This method of UsersController returns the Teachers View that shows
        /// all the active users with the "Teacher" role of the logged user school.
        /// </summary>
        /// <returns>View(List of Person usersToShow)</returns>
        public ActionResult Teachers()
        {
            return View(Utils.UsersOfRole("Teacher", User, _context));
        }

        // GET: Users/DTs
        /// <summary>
        /// This method of UsersController returns the DTs View that shows all
        /// the active users with the "ClassDirector" role of the logged user school.
        /// </summary>
        /// <returns>View(List of Person usersToShow)</returns>
        public ActionResult DTs()
        {
            return View(Utils.UsersOfRole("ClassDirector", User, _context));
        }

        // GET: Users/Create
        /// <summary>
        /// This method of UsersController returns the Create View
        /// that is used to choose wich type of user you want create.
        /// </summary>
        /// <returns>View()</returns>
        public ActionResult Create()
        {
            return View();
        }

        // GET: Users/CreateStudent
        /// <summary>
        /// This method of UsersController returns the CreateStudent View that
        /// is used to create a user of role "Student" of the logged user school.
        /// </summary>
        /// <returns>View()</returns>
        public ActionResult CreateStudent()
        {
            return View();
        }

        // POST: Users/CreateStudent
        /// <summary>
        /// This async method of UsersController returns the CreateStudent View that
        /// is used to create a user of role "Student" of the logged user school and
        /// if the user was well created, sends a success message to show.
        /// </summary>
        /// <param name="userInfo">Users form with the user info</param>
        /// <returns>View()</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateStudent(Users userInfo)
        {
            if (ModelState.IsValid)
            {
                int pin = new Random().Next(1000, 9999);
                var user = new Person { Birthdate = userInfo.Birthdate, Name = userInfo.Name, UserName = userInfo.Email, Email = userInfo.Email, SchoolName = userInfo.SchoolName, LectiveYearName = Utils.getLectiveYear(User, _context), SecondaryEmail = userInfo.SecondaryEmail, EmailConfirmed = true, ParentalPIN = pin };
                var result = await _userManager.CreateAsync(user, userInfo.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, "Student");
                    TempData["Success"] = "Estudante criado com sucesso!";

                    //enviar email para encarregado de educação
                    if (userInfo.SecondaryEmail != null) 
                    { 
                        await _emailSender.SendEmailAsync(userInfo.SecondaryEmail, "GEscola - Código Parental",
                        $"Olá, <br/>Para que possa aceder e justificar as faltas do seu educando {userInfo.Name}, é necessário aceder à plataforma GEscola e introduzir o seu código parental secreto. <br/>Código Parental: {pin} <br/>Atenciosamente,<br/>GEscola");
                    }

                    return View();
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        // GET: Users/CreateTeacher
        /// <summary>
        /// This method of UsersController returns the CreateTeacher View
        /// that is used to create a user of role "Teacher" of the logged user school.
        /// </summary>
        /// <returns>View()</returns>
        public ActionResult CreateTeacher()
        {
            return View();
        }

        // POST: Users/CreateTeacher
        /// <summary>
        /// This async method of UsersController returns the CreateTeacher View that
        /// is used to create a user of role "Teacher" of the logged user school and
        /// if the user was well created, sends a success message to show.
        /// </summary>
        /// <param name="userInfo">Users form with the user info</param>
        /// <returns>View()</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTeacher(Users userInfo)
        {
            if (ModelState.IsValid)
            {
                var user = new Person { Name = userInfo.Name, UserName = userInfo.Email, Email = userInfo.Email, SchoolName = userInfo.SchoolName, LectiveYearName = Utils.getLectiveYear(User, _context), EmailConfirmed = true };
                var result = await _userManager.CreateAsync(user, userInfo.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, "Teacher");
                    TempData["Success"] = "Professor criado com sucesso!";
                    return View();
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        /// <summary>
        /// This method of UsersController returns true if the role of user 
        /// of the given email is the same of the given role name and 
        /// returns false otherwise.
        /// </summary>
        /// <param name="email">string email of user</param>
        /// <param name="role">string role name</param>
        /// <returns>true if the role of user of the given email is the same of the given role name
        /// and returns false otherwise </returns>
        public bool isUserInRole(string email, string role)
        {
            return (Utils.getUserRole(email, _context).Equals(role));
        }


        // POST
        /// <summary>
        /// This async method of UsersController redirects to the Profile Action that 
        /// returns the Profile View of the Profile Controller and is used to generate 
        /// a new parental PIN for the user of the given email, sending an email with
        /// the pin alteration to the sponsor of education.
        /// </summary>
        /// <param name="email">string email of the user</param>
        /// <returns>Redirects to the Profile Action that returns the Profile View of 
        /// the Profile Controller</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GerarParentalPIN(string email)
        {
            email = email.Replace(" ", "@").Replace("^", ".");
            int pin = new Random().Next(1000, 9999);
            var user = _context.Users.FirstOrDefault(u => u.Email == email);

            if (user != null)
            {
                user.ParentalPIN = pin;

                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                    if (user.SecondaryEmail != null)
                    {
                        //enviar email para encarregado de educação
                        await _emailSender.SendEmailAsync(user.SecondaryEmail, "GEscola - Código Parental",
                        $"Olá, <br/>Para que possa aceder e justificar as faltas do seu educando {user.Name}, é necessário aceder à plataforma GEscola e introduzir o seu código parental secreto. <br/>Código Parental: {pin} <br/>Atenciosamente,<br/>GEscola");
                    }
                }
                catch (DbUpdateConcurrencyException) { throw; }
            }
            return RedirectToAction("Profile", "Profile", new { email = email.Replace("@", " ").Replace(".", "^") });
        }

        // GET: Users/NewLectiveYear

GEscola/GEscola/Views/Users/Create.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Person> SignInManager
@inject UserManager<Person> UserManager

@model GEscola.Models.Users

@{
    ViewData["Title"] = "Criar Utilizador";
}


<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Criar</p>

        <div class="centerTable">

            <div id="info">

                <div class="infoContainer">

                    <div class="header">
                        <ul class="options reverse">
                            <li>
                                <div class="redirectButton small">
                                    <a asp-action="Index"><img src="~/images/arrow_back_white.png" alt="Redirect" /></a>
                                </div>
                            </li>

                            <li>
                                <p class="title">Tipos de utilizador</p>
                            </li>
                        </ul>
                    </div>

                    <div class="main">

                        <ul class="choice">
                            @if (User.IsInRole("Admin"))
                            {
                                <li>
                                    <a class="container" asp-controller="Users" asp-action="CreateTeacher">
                                        <div class="containerIllustration">
                                            <div class="image teacher"></div>
                                        </div>

                                        <div class="containerText">
                                            <p>Professor</p>
                                        </div>
                                    </a>
                                </li>

                                <li>
                                    <a class="container" asp-controller="Users" asp-action="CreateStudent">
                                        <div class="containerIllustration">
                                            <div class="image student"></div>
                                        </div>

                                        <div class="containerText">
                                            <p>Aluno</p>
                                        </div>
                                    </a>
                                </li>
                            }
                        </ul>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>


<!--
<div class="containerBox">

    <div class="backBtn">
        <a asp-action="Index"><img src="~/images/back-button.png" alt="Back to List" /></a>
    </div>

    <div class="formContainer">

        <ul id="optionMenu">
            @if (User.IsInRole("Admin"))
            {
            <li>
                <a asp-controller="Users" asp-action="CreateTeacher">Professor</a>
            </li>

            <li>
                <a asp-controller="Users" asp-action="CreateStudent">Estudante</a>
            </li>
            }
        </ul>

    </div>

</div>
-->

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GEscola/GEscola/Views/Users/CreateStudent.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Person> SignInManager
@inject UserManager<Person> UserManager

@model GEscola.Models.Users
@{
    ViewData["Title"] = "Criar Aluno";
}


<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Criar</p>

        <div class="centerTable">

            <div id="info">

                <div class="infoContainer">

                    <div class="header">
                        <ul class="options reverse">
                            <li>
                                <div class="redirectButton small">
                                    <a asp-action="Index"><img src="~/images/arrow_back_white.png" alt="Redirect" /></a>
                                </div>
                            </li>

                            <li>
                                <p class="title">Aluno</p>
                            </li>
                        </ul>
                    </div>

                    <div class="main">

                        <form asp-controller="Users" asp-action="CreateStudent" asp-route-id="@Model">

                            <div class="form-group">
                                <!-- <span></span> -->
                                <input asp-for="Name" type="text" placeholder="Nome" />
                            </div>

                            <div class="form-group">
                                <!-- <span></span> -->
                                <input asp-for="Birthdate" type="date" />
                            </div>

                            <div class="form-group">
                                <!-- <span></span> -->
                                <input asp-for="SchoolName" value="@UserManager.FindByNameAsync(User.Identity.Name).Result.SchoolName" readonly="readonly" class="form-control" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/email_black.png" /></span> -->
                                <input asp-for="Email" type="email" placeholder="Email" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/email_black.png" /></span> -->
                                <input asp-for="SecondaryEmail" type="email" placeholder="Email do encarregado de educação" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/eyePassword.png" onmouseover="mouseoverPass();" onmouseout="mouseoutPass();" /></span> -->
                                <input asp-for="Password" type="password" placeholder="Password" id="passwordInput" size="30" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/eyePassword.png" onmouseover="mouseoverPass2();" onmouseout="mouseoutPass2();" /></span> -->
                                <input asp-for="ConfirmPassword" type="password" placeholder="Confirmar password" id="passwordInput2" size="30" />
                            </div>

                            <div class="form-group">
                                <input type="submit" value="@ViewData["Title"]" class="btn btn-primary submitButton" />
                            </div>

                            <div asp-validation-summary="All" class="text-danger"></div>

                            @if (TempData["Success"] != null)
                            {
                                <h4>@TempData["Success"].ToString()</h4>
                            }
                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

@section Styles {
    <link href="@Url.Content("~/css/login.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/Users/CreateTeacher.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Person> SignInManager
@inject UserManager<Person> UserManager

@model GEscola.Models.Users
@{
    ViewData["Title"] = "Criar Professor";
}


<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Criar</p>

        <div class="centerTable">

            <div id="info">

                <div class="infoContainer">

                    <div class="header">
                        <ul class="options reverse">
                            <li>
                                <div class="redirectButton small">
                                    <a asp-action="Index"><img src="~/images/arrow_back_white.png" alt="Redirect" /></a>
                                </div>
                            </li>

                            <li>
                                <p class="title">Professor</p>
                            </li>
                        </ul>
                    </div>

                    <div class="main">

                        <form asp-controller="Users" asp-action="CreateTeacher" asp-route-id="@Model">

                            <div class="form-group">
                                <!-- <span></span> -->
                                <input asp-for="Name" placeholder="Nome" type="text" class="form-control" />
                            </div>

                            <div class="form-group">
                                <!-- <span></span> -->
                                <input asp-for="SchoolName" value="@UserManager.FindByNameAsync(User.Identity.Name).Result.SchoolName" readonly="readonly" class="form-control" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/email_black.png" /></span> -->
                                <input asp-for="Email" type="email" placeholder="Email" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/eyePassword.png" onmouseover="mouseoverPass();" onmouseout="mouseoutPass();" /></span> -->
                                <input asp-for="Password" type="password" placeholder="Password" id="passwordInput" size="30" />
                            </div>

                            <div class="form-group">
                                <!-- <span><img src="~/images/eyePassword.png" onmouseover="mouseoverPass2();" onmouseout="mouseoutPass2();" /></span> -->
                                <input asp-for="ConfirmPassword" type="password" placeholder="Confirmar password" id="passwordInput2" size="30" />
                            </div>

                            <div class="form-group">
                                <input type="submit" value="@ViewData["Title"]" class="btn btn-primary submitButton" />
                            </div>

                            <div asp-validation-summary="All" class="text-danger"></div>

                            @if (TempData["Success"] != null)
                            {
                                <div>@TempData["Success"].ToString()</div>
                            }
                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

@section Styles {
    <link href="@Url.Content("~/css/login.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/Users/DTs.cshtml
@model IEnumerable<GEscola.Models.Person>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Person> SignInManager
@inject UserManager<Person> UserManager

@{
    ViewData["Title"] = "Index";
}

<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Lista de DTs</p>

        <div class="centerTable">

            <div id="tableOptions">
                
                <div id="filtersBox">
                    <ul class="filters">
                        <li>
                            <a asp-action="Index">Todos</a>
                        </li>

                        <li>
                            <a asp-action="Students">Alunos</a>
                        </li>

                        <li>
                            <a asp-action="Teachers">Professores</a>
                        </li>

                        <li class="choosen">
                            <a asp-action="DTs">DT's</a>
                        </li>
                    </ul>
                </div>
            </div>


            <table>
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Escola</th>
                        <th>Detalhes</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th>Editar</th>
                            <th>Eliminar</th>
                        }
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SchoolName)
                            </td>
                            <td>
                                <a asp-controller="Profile" asp-action="Profile" asp-route-email="@item.Email.Replace("@", " ").Replace(".", "^")"><img src="~/images/info.png" alt="Details" /></a>
                            </td>
                            @if (User.IsInRole("Admin"))
                            {
                                <td>
                                    <a asp-action="Edit" asp-route-id="@UserManager.FindByEmailAsync(item.Email).Result.Id"><img src="~/images/edit.png" alt="Edit" /></a>
                                </td>
                                <td>
                                    <a asp-action="Delete" asp-route-id="@UserManager.FindByEmailAsync(item.Email).Result.Id"><img src="~/images/delete.png" alt="Delete" /></a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>

        </div>

    </div>
</div>

GEscola/GEscola/Views/Users/Delete.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Person> SignInManager
@inject UserManager<Person> UserManager
@model GEscola.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Eliminar</p>

        <div class="centerTable">

            <div class="backBtn">
                <a asp-action="Index"><img src="~/images/back-button.png" alt="Back to List" /></a>
            </div>

            <p>Tem a certeza que pretende eliminar este utilizador?</p>

            <table>
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.Name)
                        </td>

                        <td>
                            @Html.DisplayFor(model => model.Email)
                        </td>
                    </tr>
                </tbody>
            </table>

            <br /><br /><br />
            <div class="formContainer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Email" />
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </form>
            </div>

        </div>

    </div>

</div>

GEscola/GEscola/Views/Users/NewLectiveYear.cshtml
@model GEscola.Models.LectiveYearViewModel

@{
    ViewData["Title"] = "Criação de um novo ano letivo";
}

<div class="containerBox">

    <div class="formContainer">

        <div id="profileContainer">

            <div>
                <center>
                    <span><b>@ViewData["Title"]</b></span>
                    <br/>
                </center>
            </div>
            
            @if (User.IsInRole("Admin"))
            {
                <form asp-controller="Users" asp-action="NewLectiveYear">

                    <h1>Tem a certeza que deseja iniciar um novo ano letivo?</h1>
            
                    <div class="form-group">
                        <label class="no-margin">Nome para o Novo Ano Letivo</label>
                        <input asp-for="NewLectiveYear" type="text" placeholder="(Ex: 2020/2021)" />
                    </div>

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input style="width:auto" id="changePassword" type="submit" value="Iniciar Novo Ano Letivo" class="btn btn-primary" />
                </form>
            }
            <center>
                <a class="btn btn-primary" style="background-color:red; font-size:20px" asp-controller="Home" asp-action="Index">Cancelar</a>
            
                <div id="warningRectangle">
                    <p>Ao efetuar esta esta operação serão apagadas todas as Aulas e Faltas de Alunos</p>
                    <p>As Turmas e as Pautas de Avaliações serão colocadas em histórico</p>
                </div>
            </center>
            <br/>

        </div>
    </div>
</div>



@section Styles {
    <link href="@Url.Content("~/css/register.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/newYear.css")" rel="stylesheet" type="text/css" />
}