GEscola/GEscola/Controllers/SchoolClassesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GEscola.Data;
using GEscola.Models;
using Microsoft.AspNetCore.Identity;
using System.Diagnostics;

namespace GEscola.Controllers
{
    public class SchoolClassesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Person> _userManager;

        public SchoolClassesController(ApplicationDbContext context, UserManager<Person> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: SchoolClasses
        /// <summary>
        /// This async method of SchoolClassesController returns the Index View
        /// that shows all school classes of the logged user school, of the actual lective year.
        /// </summary>
        /// <returns>View(List of SchoolClass schoolClassesToShow)</returns>
        public async Task<IActionResult> Index()
        {
            return View(ConvertSchoolClassToOP(await _context.SchoolClass.Where(sc => sc.isDeleted == false && sc.SchoolName == Utils.getSchoolName(User, _context) && sc.LectiveYear == Utils.getLectiveYear(User, _context)).ToListAsync()));
        }

        // GET: SchoolClasses/Historic
        /// <summary>
        /// This async method of SchoolClassesController returns the Historic View
        /// that shows all school classes of the logged user school, of the previous lective years.
        /// </summary>
        /// <returns>View(List of SchoolClass schoolClassesToShow)</returns>
        public async Task<IActionResult> Historic()
        {
            return View(ConvertSchoolClassToOP(await _context.SchoolClass.Where(sc => sc.isDeleted == false && sc.SchoolName == Utils.getSchoolName(User, _context) && sc.LectiveYear != Utils.getLectiveYear(User, _context)).ToListAsync()));
        }

        // GET: SchoolClasses/Details/5
        /// <summary>
        /// This async method of SchoolClassesController returns the Details View
        /// that shows with details the school class with the given id.
        /// </summary>
        /// <param name="id">int id of the school class</param>
        /// <returns>View(SchoolClassOP schoolClassToShow)</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var schoolClass = await _context.SchoolClass.FirstOrDefaultAsync(m => m.SchoolClassId == id);
            if (schoolClass == null) return NotFound();

            SchoolClassOP sc = new SchoolClassOP { SchoolClass = schoolClass, CourseName = GetCourseName(schoolClass.CourseId), TeacherName = GetTeacherName(schoolClass.TeacherId), StudentsList = SchoolClassStudentsToPersonList(schoolClass)};

            return View(sc);
        }

        /// This method of SchoolClassesController returns the list of users with
        /// Teacher role of the logged user school.
        /// </summary>
        /// <returns>List of SelectListItem usersOfRoleTeacher</returns>
        public List<SelectListItem> GetListOfTeachers()
        {
            List<SelectListItem> listTeachers = new List<SelectListItem>();
            foreach (Person p in Utils.UsersOfRole("Teacher", User, _context))
            {
                listTeachers.Add(new SelectListItem { Text = p.Name, Value = p.Id });
            }
            return listTeachers;
        }

        /// <summary>
        /// This method of SchoolClassesController returns the name of the
        /// user of the given id and of the logged user school.
        /// </summary>
        /// <param name="id">string id of the user</param>
        /// <returns>string name of the user</returns>
        public string GetTeacherName(string id)
        {
            var user = _context.Users.FirstOrDefault(u => u.Id == id && u.isDeleted == false && u.SchoolName == Utils.getSchoolName(User, _context));
            return (user != null) ? user.Name : "Não Atribuído";
        }

        /// <summary>
        /// This method of SchoolClassesController returns the name of the
        /// course of the given id and of the logged user school.
        /// </summary>
        /// <param name="id">string id of the course</param>
        /// <returns>string name of the course</returns>
        public string GetCourseName(int id)
        {
            var course = _context.Course.FirstOrDefault(u => u.CourseId == id && u.isDeleted == false && u.SchoolName == Utils.getSchoolName(User, _context));
            return course.Name;
        }

        /// <summary>
        /// This method of SchoolClassesController converts a List of SchoolClass model
        /// to a List of SchoolClassOP model and returns the converted List.
        /// </summary>
        /// <param name="schoolClasses">List of SchoolClass model</param>
        /// <returns>List of SchoolClassOP converted</returns>
        public List<SchoolClassOP> ConvertSchoolClassToOP(List<SchoolClass> schoolClasses)
        {
            List<SchoolClassOP> scList = new List<SchoolClassOP>();
            foreach (var sc in schoolClasses)
            {
                scList.Add(new SchoolClassOP { SchoolClass = sc, CourseName = GetCourseName(sc.CourseId), TeacherName = GetTeacherName(sc.TeacherId) });
            }
            return scList;
        }

        // GET: SchoolClasses/Create
        /// <summary>
        /// This method of SchoolClassesController returns the Create View that
        /// is used to create a school class for the logged user school.
        /// </summary>
        /// <returns>View()</returns>
        public IActionResult Create()
        {
            ViewBag.courses = Utils.GetListOfCourses(User, _context);
            ViewBag.teachers = GetListOfTeachers();
            return View();
        }

        // POST: SchoolClasses/Create
        /// <summary>
        /// This async method of SchoolClassesController redirects to the Index View 
        /// that shows all the active school classes for the logged user school if the school class
        /// was well created, otherwise returns the same View with the respective errors. <br/>
        /// This method is used to create a school class with the given form info.
        /// </summary>
        /// <param name="schoolClass">SchoolClass form with the school class info</param>
        /// <returns>Redirects to the Index View if the school class was well created,
        /// otherwise returns the same View</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SchoolClass schoolClass)
        {
            if (ModelState.IsValid)
            {
                var schoolName = Utils.getSchoolName(User, _context);
                var sc = new SchoolClass { SchoolName = schoolName, Name = schoolClass.Name, CourseId = schoolClass.CourseId, LectiveYear = Utils.getLectiveYear(User, _context) };
                if (schoolClass.TeacherId != "null") sc.TeacherId = schoolClass.TeacherId;
                _context.Add(sc);
                await _context.SaveChangesAsync();
                if (schoolClass.TeacherId != "null")
                {
                    Debug.WriteLine("#11## " + schoolClass.TeacherId);
                    Debug.WriteLine("#11## " + schoolName);
                    var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == schoolClass.TeacherId && u.SchoolName == schoolName);
                    Debug.WriteLine("#22## " + user);
                    await _userManager.AddToRoleAsync(user, "ClassDirector");
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.courses = Utils.GetListOfCourses(User, _context);
            ViewBag.teachers = GetListOfTeachers();
            return View(schoolClass);
        }

        /// <summary>
        /// This method of SchoolClassesController converts the string of SchoolClassStudents
        /// to a List of Person, returning it.
        /// </summary>
        /// <param name="schoolClass">SchoolClass that contains the string of SchoolClassStudents</param>
        /// <returns>List of Person converted</returns>
        public List<Person> SchoolClassStudentsToPersonList(SchoolClass schoolClass)
        {
            string students = schoolClass.Students;
            if (students == null) students = "";
            List<string> stringStudentList = new List<string>(students.Split('|'));

            List<Person> allStudentsList = new List<Person>(Utils.UsersOfRole("Student", User, _context).OfType<Person>());
            List<Person> studentsList = new List<Person>();

            foreach (var studentEmail in stringStudentList)
            {
                Person student = allStudentsList.FirstOrDefault(student => student.Email.Equals(studentEmail));
                if (student != null && student.Email.Equals(studentEmail)) studentsList.Add(student);

            }
            return studentsList;
        }

        /// <summary>
        /// This method of SchoolClassesController removes the student of the 
        /// given email of string of the given SchoolClassStudents, returning 
        /// the updated string.
        /// </summary>
        /// <param name="stringList">string of school class students</param>
        /// <param name="studentEmail">string email of the student to remove</param>
        /// <returns>string of the updated SchoolClassStudents</returns>
        public string RemoveStudentOfStringList(string stringList, string studentEmail)
        {
            return stringList.Replace(studentEmail + "|", "");
        }

        /// <summary>
        /// This method of SchoolClassesController adds the student of the 
        /// given email into the string of the given SchoolClassStudents, returning 
        /// the updated string.

GEscola/GEscola/Views/SchoolClasses/AddStudent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

GEscola/GEscola/Views/SchoolClasses/Create.cshtml
@model GEscola.Models.SchoolClass

@{
    ViewData["Title"] = "Criar";
}


<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Criar</p>

        <div class="centerTable">

            <div id="info">

                <div class="infoContainer">

                    <div class="header">
                        <ul class="options reverse">
                            <li>
                                <div class="redirectButton small">
                                    <a asp-action="Index"><img src="~/images/arrow_back_white.png" alt="Redirect" /></a>
                                </div>
                            </li>

                            <li>
                                <p class="title">Turma</p>
                            </li>
                        </ul>
                    </div>

                    <div class="main">

                        <form asp-action="Create">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input asp-for="Name" type="text" class="form-control" />
                            </div>

                            <div class="form-group">
                                <label asp-for="CourseId"></label>
                                <select class="select" asp-for="CourseId" asp-items=@ViewBag.courses>
                                    <option>- Selecione -</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label asp-for="TeacherId"></label>
                                <select class="select" asp-for="TeacherId" asp-items=@ViewBag.teachers>
                                    <option value="null">- Selecione -</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Criar" class="btn btn-primary submitButton" />
                            </div>

                            <div asp-validation-summary="All" class="text-danger"></div>
                        </form>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
@section Styles {
    <link href="@Url.Content("~/css/login.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/SchoolClasses/Delete.cshtml
@model GEscola.Models.SchoolClassOP

@{
    ViewData["Title"] = "Delete";
}

<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Eliminar</p>

        <div class="centerTable">

            <div class="backBtn">
                <a asp-action="Index"><img src="~/images/back-button.png" alt="Back to List" /></a>
            </div>

            <p>Tem a certeza que pretende eliminar esta turma?</p>

            <table>
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.SchoolClass.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TeacherName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CourseName)
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.SchoolClass.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.TeacherName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.CourseName)
                        </td>
                    </tr>
                </tbody>
            </table>
            <br /><br /><br />
            <div class="formContainer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="SchoolClass.SchoolClassId" />
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </form>
            </div>

        </div>

    </div>

</div>

@section Styles {
    <link href="@Url.Content("~/css/login.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/SchoolClasses/Details.cshtml
@model GEscola.Models.SchoolClassOP

@{
    ViewData["Title"] = "Detalhes";
}


<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Detalhes</p>

        <div class="centerTable">

            <div id="info">

                <div class="infoContainer">

                    <div class="header">

                        <ul class="options reverse">
                            <li>
                                <div class="redirectButton small">
                                    <a asp-action="Index"><img src="~/images/arrow_back_white.png" alt="Redirect" /></a>
                                </div>
                            </li>

                            <li>
                                <p class="title">Turma</p>
                            </li>
                        </ul>

                        <ul class="options">
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="iconBtn">
                                    <a asp-action="Edit" asp-route-id="@Model.SchoolClass.SchoolClassId"><img src="~/images/edit.png" alt="Editar" /></a>
                                </li>
                            }
                        </ul>
                    </div>

                    <div class="main">

                        <ul>
                            <li>
                                <label>Ano Letivo</label>
                                <p>@Html.DisplayFor(model => model.SchoolClass.LectiveYear)</p>
                            </li>

                            <li>
                                <label>Nome da turma</label>
                                <p>@Html.DisplayFor(model => model.SchoolClass.Name)</p>
                            </li>

                            <li>
                                <label>Nome do professor</label>
                                <p>@Html.DisplayFor(model => model.TeacherName)</p>
                            </li>

                            <li>
                                <label>Nome do curso</label>
                                <p>@Html.DisplayFor(model => model.CourseName)</p>
                            </li>

                            <li>
                                <label>Estudantes</label>

                                <table>
                                    <thead>
                                        <tr>
                                            <th>
                                                Nome
                                            </th>
                                            <th>
                                                Email
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (Person student in Model.StudentsList)
                                        {
                                            <tr>
                                                <td>
                                                    @student.Name
                                                </td>
                                                <td>
                                                    @student.Email
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </li>
                        </ul>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

@section Styles {
    <link href="@Url.Content("~/css/login.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/SchoolClasses/Edit.cshtml
@model GEscola.Models.SchoolClass

@{
    ViewData["Title"] = "Editar";
}

<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Editar</p>

        <div class="centerTable">

            <div id="info">

                <div class="infoContainer">

                    <div class="header">
                        <ul class="options reverse">
                            <li>
                                <div class="redirectButton small">
                                    <a asp-action="Index"><img src="~/images/arrow_back_white.png" alt="Redirect" /></a>
                                </div>
                            </li>

                            <li>
                                <p class="title">Turma</p>
                            </li>
                        </ul>
                    </div>

                    <div class="main">

                        <form asp-action="Edit">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <input type="hidden" asp-for="SchoolClassId" />
                            <input type="hidden" asp-for="SchoolName" />
                            <input type="hidden" asp-for="Students" />
                            <input type="hidden" asp-for="LectiveYear" />

                            <input type="hidden" id="oldTeacherId" name="oldTeacherId" value="@ViewContext.HttpContext.Request.Query["oldTeacherId"]" />

                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="CourseId"></label>
                                <select class="select" asp-for="CourseId" asp-items=@ViewBag.courses></select>
                            </div>

                            <div class="form-group">
                                <label asp-for="TeacherId"></label>
                                <select class="select" asp-for="TeacherId" asp-items=@ViewBag.teachers></select>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Guardar" class="btn btn-primary submitButton" />
                            </div>

                        </form>
                        <div class="newBox">
                            @using (Html.BeginForm("AddStudent", "SchoolClasses", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Adicionar Estudante</label>

                                    <div class="addInput">
                                        <input type="text" name="studentEmail" id="studentEmail" class="form-control f1f1f1" placeholder="Email" />
                                        <input type="hidden" name="id" id="id" value="@Model.SchoolClassId" />
                                        <input type="submit" value="+" class="normalInputButton" />
                                    </div>
                                </div>
                            }

                            <table class="marginTop5">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>Email</th>
                                        <th>Remover</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Person student in ViewBag.students)
                                    {
                                        <tr>
                                            <td>
                                                @student.Name
                                            </td>
                                            <td>
                                                @student.Email
                                            </td>
                                            <td>
                                                <a asp-action="RemoveStudent" asp-route-id="@Model.SchoolClassId" asp-route-studentEmail="@student.Email.Replace("@", " ").Replace(".", "^")"><img src="~/images/delete.png" alt="Delete" /></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@section Styles {
    <link href="@Url.Content("~/css/login.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/SchoolClasses/Historic.cshtml
@model IEnumerable<GEscola.Models.SchoolClassOP>

@{
    ViewData["Title"] = "Turmas";
}

<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Lista de turmas</p>

        <div class="centerTable">

            <div id="tableOptions">

                <div id="filtersBox">
                    <ul class="filters">
                        <li>
                            <a asp-action="Index">Ano Letivo Atual</a>
                        </li>

                        <li class="choosen">
                            <a>Histórico</a>
                        </li>
                    </ul>
                </div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.SchoolClass.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CourseName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TeacherName)
                        </th>
                        <th>
                            Detalhes
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.SchoolClass.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CourseName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TeacherName)
                            </td>
                            <td>
                                <a asp-action="Details" asp-route-id="@item.SchoolClass.SchoolClassId"><img src="~/images/info.png" alt="Details" /></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

GEscola/GEscola/Views/SchoolClasses/Index.cshtml
@model IEnumerable<GEscola.Models.SchoolClassOP>

@{
    ViewData["Title"] = "Turmas";
}

<div class="containerBox">

    <div id="tableContainer">

        <p class="tableTitle">Turmas</p>

        <div class="centerTable">

            <div id="tableOptions">
                @if (User.IsInRole("Admin"))
                {
                    <div class="backBtn">
                        <a asp-action="Create"><img src="~/images/add.png" alt="Create New" /></a>
                    </div>
                }
            </div>
            <div id="filtersBox">
                <ul class="filters">
                    <li class="choosen">
                        <a>Ano Letivo Atual</a>
                    </li>

                    <li>
                        <a asp-action="Historic">Histórico</a>
                    </li>
                </ul>
            </div>

            <div class="row">

                @foreach (var item in Model)
                {
                    <div class="column">
                        <div class="card">
                            <center>
                                <div class="container">
                                    <h2><b>@Html.DisplayFor(modelItem => item.SchoolClass.Name)</b></h2>
                                    <p><b>@Html.DisplayFor(modelItem => item.CourseName)</b></p>
                                    <p>@Html.DisplayFor(modelItem => item.TeacherName)</p>
                                </div>

                                <img src="~/images/classroom2.png" alt="Avatar" class="classImg">

                                <hr>
                                <div class="divIcons">
                                    <a asp-action="Details" asp-route-id="@item.SchoolClass.SchoolClassId"><img src="~/images/info.png" alt="Details" /></a>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <a class="iconFirstImage" asp-action="Edit" asp-route-id="@item.SchoolClass.SchoolClassId"><img src="~/images/edit.png" alt="Edit" /></a>
                                        <a class="iconsImage" asp-action="Delete" asp-route-id="@item.SchoolClass.SchoolClassId"><img src="~/images/delete.png" alt="Delete" /></a>
                                    }
                                </div>
                            </center>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@section Styles {
    <link href="@Url.Content("~/css/schoolclasses.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/SchoolClasses/RemoveStudent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}