GEscola/GEscola/Models/Grade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GEscola.Models
{
    public class Grade
    {
        
        [Display(Name = "ID das Notas")]
        public int GradeId { get; set; }

        [Display(Name = "Ano Letivo")]
        public string LectiveYear { get; set; }

        public string SchoolName { get; set; }

        [Required]
        [Display(Name = "ID da Avaliação")]
        public int EvaluationID { get; set; }

        [Required]
        [Display(Name = "ID do Aluno")]
        public string StudentID { get; set; }

        [Display(Name = "ID da UC")]
        public int UCID { get; set; }

        [Range(0, 20, ErrorMessage = "O valor para {0} deve estar entre {1} e {2}.")]
        [Display(Name = "Nota")]
        public int GradeNumber { get; set; }
        
    }
}

GEscola/GEscola/Controllers/GradesController.cs
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using GEscola.Data;
using GEscola.Models;
using System.Data;
using IronPdf;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace GEscola.Controllers
{
    public class GradesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ICompositeViewEngine _viewEngine;

        public GradesController(ApplicationDbContext context, ICompositeViewEngine viewEngine)
        {
            _context = context;
            _viewEngine = viewEngine;
        }

        //ViewBag List of UC's 
        /// <summary>
        /// This method of GradesController returns the list of UCs, of the logged user school,
        /// of the given Evaluation.
        /// </summary>
        /// <param name="evaluation">Evaluation evaluation to find</param>
        /// <returns>List of UC ucsOfAnEvaluation</returns>
        public List<UC> GetListOfUCs(Evaluation evaluation)
        {
            var schoolName = Utils.getSchoolName(User, _context);
            var stringOfUCs = _context.Course.FirstOrDefault(c => c.CourseId == evaluation.CourseId && c.SchoolName == schoolName).UCs;
            List<string> list = new List<string>(stringOfUCs.Split('|'));


            List<UC> listOfUCs = new List<UC>();
            foreach (UC uc in _context.UC.Where(u => u.SchoolName == schoolName).OrderBy(uc => uc.Name))
            {
                if (list.Contains(uc.UCId.ToString())) listOfUCs.Add(uc);
            }
            return listOfUCs;
        }

        // GET: Grade/Create
        /// <summary>
        /// This method of GradesController returns the Create View that
        /// is used to create a grade for the Evaluation that contains the given
        /// courseId and classId, for the logged user school.
        /// </summary>
        /// <param name="courseID">int courseId to find</param>
        /// <param name="classID">int classID to find</param>
        /// <returns>View(GradeOP gradeOP)</returns>
        public IActionResult Create(int courseID, int classID)
        {
            var actualLectiveYear = Utils.getLectiveYear(User, _context);
            var schoolName = Utils.getSchoolName(User, _context);
            var evaluation = _context.Evaluation.FirstOrDefault(e => e.CourseId == courseID && e.SchoolClassId == classID && e.SchoolName == schoolName && e.LectiveYear == actualLectiveYear);
            var courseName = _context.Course.FirstOrDefault(c => c.CourseId == evaluation.CourseId && c.SchoolName == schoolName).Name;
            var className = _context.SchoolClass.FirstOrDefault(sc => sc.SchoolClassId == evaluation.SchoolClassId && sc.SchoolName == schoolName && sc.LectiveYear == actualLectiveYear).Name;
            ViewBag.courseName = courseName;
            ViewBag.className = className;
            ViewBag.ucs = GetListOfUCs(evaluation);
            ViewBag.students = Utils.GetStudentsInClass(evaluation.SchoolClassId, User, _context);
            GradeOP gradeOP = new GradeOP { GradesList = GetListOfGradesUsingEvaluation(evaluation) };

            return View(gradeOP);
        }

        // POST: Grades/Create
        /// <summary>
        /// This async method of GradesController redirects to the Index View of the EvaluationsController 
        /// that shows all the evaluations of the logged user school. <br/>
        /// This method is used to create all grades with the given form info.
        /// </summary>
        /// <param name="gradeOP">GradeOP form with the grades info</param>
        /// <returns>Redirects to the Index View of the EvaluationsController</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GradeOP gradeOP)
        {
            foreach(Grade grade in gradeOP.GradesList)
            {
                if(grade.GradeNumber >= 0 && grade.GradeNumber <= 20)
                {
                    grade.SchoolName = Utils.getSchoolName(User, _context);
                    grade.LectiveYear = Utils.getLectiveYear(User, _context);
                    _context.Add(grade);
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Evaluations");            
        }

        /// <summary>
        /// This method of GradesController returns an empty list of grades for an evaluation form.
        /// </summary>
        /// <param name="evaluation">Evaluation evaluation to get all grades</param>
        /// <returns>List of Grade evaluationGradesEmptyList</returns>
        public List<Grade> GetListOfGradesUsingEvaluation(Evaluation evaluation)
        {
            List<Grade> list = new List<Grade>();
            var ucs = GetListOfUCs(evaluation);
            var students = Utils.GetStudentsInClass(evaluation.SchoolClassId, User, _context);

            foreach (Person p in students)
            {
                foreach (UC uc in ucs)
                {
                    list.Add(new Grade { SchoolName = Utils.getSchoolName(User, _context), LectiveYear = Utils.getLectiveYear(User, _context), EvaluationID = evaluation.EvaluationId, StudentID = p.Id, UCID = uc.UCId, GradeNumber = 0 });

                }
            }
            return list;
        }

        /// <summary>
        /// This method of GradesController returns the list of grades for of the given evaluation id.
        /// </summary>
        /// <param name="evaluationID">int evaluationId to find</param>
        /// <returns>List of Grade evaluationGradesList</returns>
        public List<Grade> GetListOfGrades(int evaluationID)
        {
            List<Grade> list = new List<Grade>();
            var grades = _context.Grade.Where(g => g.EvaluationID == evaluationID && g.SchoolName == Utils.getSchoolName(User, _context) && g.LectiveYear == Utils.getLectiveYear(User, _context));
            foreach (Grade g in grades)
            {
                list.Add(g);
            }
            return list;
        }


        /// <summary>
        /// This method of EvaluationsController returns the user grades average with the given student email.
        /// </summary>
        /// <returns>float grades average of the user</returns>
        public float GetStudentAverage(string studentEmail)
        {
            var student = _context.Users.FirstOrDefault(u => u.Email == studentEmail);

            List<int> grades = new List<int>();
            foreach (var g in _context.Grade.Where(g => g.StudentID == student.Id).ToList())
            {
                grades.Add(g.GradeNumber);
            }

            return ((float)grades.Sum() / (float)grades.Count());
        }

        /// <summary>
        /// This method of EvaluationsController returns the Dictionary of PersonKey and floatValue
        /// that contains the grade average of each student based on the evaluations already created,
        /// of the logged user school, of the actual lective year.
        /// </summary>
        /// <returns>Dictionary of PersonKey and floatValue studentsGradesAverage</returns>
        public Dictionary<Person, float> studentsAverage()
        {
            var map = new Dictionary<Person, float>();

            List<int> schoolClassIDsInEvaluations = new List<int>();
            List<SchoolClass> schoolClassesInEvaluations = new List<SchoolClass>();
            foreach (Evaluation e in _context.Evaluation.Where(u => u.SchoolName == Utils.getSchoolName(User, _context) && u.LectiveYear == Utils.getLectiveYear(User, _context)))
            {
                if (!schoolClassIDsInEvaluations.Contains(e.SchoolClassId))
                {
                    schoolClassIDsInEvaluations.Add(e.SchoolClassId);
                    schoolClassesInEvaluations.Add(_context.SchoolClass.FirstOrDefault(s => s.SchoolClassId == e.SchoolClassId && s.LectiveYear == Utils.getLectiveYear(User, _context)));
                }
            }

            List<Person> studentsList = new List<Person>();
            foreach (SchoolClass sc in schoolClassesInEvaluations)
            {
                studentsList.AddRange(Utils.GetStudentsInClass(sc.SchoolClassId, User, _context));
            }

            foreach (Person p in studentsList)
            {
                map.Add(p, GetStudentAverage(p.Email));
            }
            return map;
        }

        /// <summary>
        /// This method of EvaluationsController returns the Dictionary of PersonKey and floatValue
        /// that contains the grade average of the best student based on the evaluations of the
        /// school class with the given school class id, of the logged user school, of the actual lective year.
        /// </summary>
        /// <param name="schoolClassId">int schoolClassId to find students of the school class</param>
        /// <returns>Dictionary of PersonKey and floatValue of the grade average of the best student</returns>
        public Dictionary<Person, float> bestStudentAverageOfSchoolClass(int schoolClassId)
        {
            var findingBest = new Dictionary<Person, float>();
            Person bestStudent = null;
            float bestAverage = -1;
            foreach (Person p in Utils.GetStudentsInClass(schoolClassId, User, _context))
            {
                var avg = GetStudentAverage(p.Email);
                if (avg > bestAverage)
                {
                    bestAverage = avg;
                    bestStudent = p;
                }
            }

            findingBest.Add(bestStudent, bestAverage);
            return findingBest;
        }

        /// <summary>
        /// This method of EvaluationsController returns the Dictionary of PersonKey and floatValue
        /// that contains the grade average of the worst student based on the evaluations of the

GEscola/GEscola/Views/Grades/Create.cshtml
@model GEscola.Models.GradeOP

@{ ViewData["Title"] = "Create"; }


<div class="containerBox">

    <div class="backBtn">
        <a asp-controller="Evaluations" asp-action="InitialCreate"><img src="~/images/back-button.png" alt="Back to List" /></a>
    </div>
    <div class="formContainer">

        <div class="headerLog">
            <center><span><b>Pauta da turma @ViewBag.className do curso @ViewBag.courseName </b></span></center> <!--ALTERAR PARA OS NOMES!!!!!!!!!!!!!!!!!-->
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <form asp-action="Create">
            <table>
                <thead>
                    <tr>
                        <th> Nome </th>
                        <th> Email </th>
                        @foreach (var item in ViewBag.ucs)
                        {
                            <th>
                                @(item.Name)
                            </th>
                        }
                    </tr>
                </thead>


                <tbody>
                    @{
                        List<Person> students = ViewBag.students as List<Person>;
                        List<UC> ucs = ViewBag.ucs as List<UC>;
                        foreach (Person p in students)
                        {
                            <tr>
                                <td>@p.Name</td>
                                <td>@p.Email</td>
                                @for (var i = 0; i < Model.GradesList.Count; i++)
                                {
                                    @if (Model.GradesList[i].StudentID == p.Id)
                                    {
                                        @if (ucs.Any(u => u.UCId == Model.GradesList[i].UCID))
                                        {
                                            <td>
                                                <input type="number" asp-for="@Model.GradesList[i].GradeNumber" min="0" max="20">

                                                <input type="hidden" asp-for="@Model.GradesList[i].GradeId" />
                                                <input type="hidden" asp-for="@Model.GradesList[i].EvaluationID" />
                                                <input type="hidden" asp-for="@Model.GradesList[i].StudentID" />
                                                <input type="hidden" asp-for="@Model.GradesList[i].UCID" />
                                            </td>
                                        }
                                    }

                                }
                            </tr>
                            }
                        }


                    </tbody>
                </table>

                <input type="submit" value="Criar" class="btn btn-primary" />
                <div asp-validation-summary="All" class="text-danger"></div>
            </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GEscola/GEscola/Views/Grades/PreviewPDF.cshtml
@model GEscola.Models.GradeOP

@{ ViewData["Title"] = "Export"; }


<div class="containerBox">

    <div class="backBtn" style="margin-top:50px"> 
        <a asp-controller="Evaluations" asp-action="Index"><img src="~/images/back-button.png" alt="Back to List" /></a>
    </div>
    <div class="formContainer">
        <div>
        </div>
        <div>
            <h5 style="margin-bottom: 180px;">Média das notas do melhor e pior aluno</h5>
            <div class="box">

                @{
                    var best = ViewBag.bestStudent as Dictionary<Person, float>;
                    foreach (Person p in best.Keys)
                    {
                        float barHeight = (best.GetValueOrDefault(p) * 100) / 20;
                        string convert = barHeight.ToString().Replace(",", ".") + "%";
                        <div class="skill">
                            <div class="graph" style="height: @convert">
                                <div class="percent">@best.GetValueOrDefault(p)</div>
                            </div>
                            <div id="names">@p.Name</div>
                        </div>
                    }


                    var worst = ViewBag.worstStudent as Dictionary<Person, float>;
                    foreach (Person p in worst.Keys)
                    {
                        float barHeight = (worst.GetValueOrDefault(p) * 100) / 20;
                        string convert = barHeight.ToString().Replace(",", ".") + "%";
                        <div class="skill">
                            <div class="graph" style="height: @convert">
                                <div class="percent">@worst.GetValueOrDefault(p)</div>
                            </div>
                            <div id="names">@p.Name</div>
                        </div>
                    }
                }

            </div>
        </div>

        <div class="headerLog">
            <center><span><b>Pauta da turma @ViewBag.className do curso @ViewBag.courseName </b></span></center> <!--ALTERAR PARA OS NOMES!!!!!!!!!!!!!!!!!-->
        </div>
        <div class="previewTable">
            <table>
                <thead>
                    <tr>
                        <th> Nome </th>
                        <th> Email </th>
                        @foreach (var item in ViewBag.ucs)
                        {
                            <th>
                                @(item.Name)
                            </th>
                        }
                    </tr>
                </thead>


                <tbody>
                    @{
                        List<Person> students = ViewBag.students as List<Person>;
                        List<UC> ucs = ViewBag.ucs as List<UC>;
                        foreach (Person p in students)
                        {
                            <tr>
                                <td>@p.Name</td>
                                <td>@p.Email</td>
                                @for (var i = 0; i < Model.GradesList.Count; i++)
                                {
                                    @if (Model.GradesList[i].StudentID == p.Id)
                                    {
                                        @if (ucs.Any(u => u.UCId == Model.GradesList[i].UCID))
                                        {
                                            <td>
                                                @Model.GradesList[i].GradeNumber
                                            </td>
                                        }
                                    }

                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <!--
            <div style="margin-top: 10px;">
                <a asp-controller="Grades" asp-action="PrintPDF" asp-route-courseID="@@ViewBag.courseID" asp-route-classID="@@ViewBag.classID" class="btn  btn-success"><img src="~/images/download.png" alt="Back to List" /></a>
            </div>
        -->
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@section Styles {
    <link href="@Url.Content("~/css/evaluations.css")" rel="stylesheet" type="text/css" />
}

GEscola/GEscola/Views/Grades/PrintPDF.cshtml
@model GEscola.Models.GradeOP

@{ ViewData["Title"] = "Export"; }


<div class="containerBox">

    <div class="backBtn">
        <a asp-controller="Evaluations" asp-action="Index"><img src="~/images/back-button.png" alt="Back to List" /></a>
    </div>
    <div class="formContainer">

        <div class="headerLog">
            <center><span><b>Pauta @Model.GradesList[0].LectiveYear da turma @ViewBag.className do curso @ViewBag.courseName </b></span></center> <!--ALTERAR PARA OS NOMES!!!!!!!!!!!!!!!!!-->
        </div>


        <div>
            @{
                var best = ViewBag.bestStudent as Dictionary<Person, float>;
                foreach (Person p in best.Keys)
                {
                    <p>@p.Name</p>
                    <p>@best.GetValueOrDefault(p)</p>
                }


                var worst = ViewBag.worstStudent as Dictionary<Person, float>;
                foreach (Person p in worst.Keys)
                {
                    <p>@p.Name</p>
                    <p>@worst.GetValueOrDefault(p)</p>
                }
            }
        </div>

        <table>
            <thead>
                <tr>
                    <th> Nome </th>
                    <th> Email </th>
                    @foreach (var item in ViewBag.ucs)
                    {
                        <th>
                            @(item.Name)
                        </th>
                    }
                </tr>
            </thead>


            <tbody>
                @{
                    List<Person> students = ViewBag.students as List<Person>;
                    List<UC> ucs = ViewBag.ucs as List<UC>;
                    foreach (Person p in students)
                    {
                        <tr>
                            <td>@p.Name</td>
                            <td>@p.Email</td>
                            @for (var i = 0; i < Model.GradesList.Count; i++)
                            {
                                @if (Model.GradesList[i].StudentID == p.Id)
                                {
                                    @if (ucs.Any(u => u.UCId == Model.GradesList[i].UCID))
                                    {
                                        <td>
                                            @Model.GradesList[i].GradeNumber
                                        </td>
                                    }
                                }

                            }
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}